# Generated by Django 5.0.6 on 2024-08-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('dashboard', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.blogpost'),
        ),
    ]
